
- name: app setup 
  include_role:
    name: common
    tasks_from: app_setup

- name: install nodejs
  include_role:
    name: common
    tasks_from: nodejs

- name: systemd setup
  include_role:
    name: common
    tasks_from: systemd
    
- name: copy the mongodb repo
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: install the mongodb server
  ansible.builtin.dnf:
    name: mongodb-mongosh
    state: present

- name: check produscts loaded or not from mongodb
  ansible.builtin.command: mongosh --host mongodb.kotadurgagangumalla.fun --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
  register: catalogue_output

- name: print the catalogue output
  ansible.builtin.debug:
    msg: "{{catalogue_output}}"

- name: load the data
  ansible.builtin.shell: mongosh --host mongodb.kotadurgagangumalla.fun < /app/db/master-data.js
  when: catalogue_output.stdout | int < 0