# - name: disable the nodejs module
#   ansible.builtin.command: dnf module disable nodejs -y

# - name: enable the nodejs module
#   ansible.builtin.command: dnf module enable nodejs:20 -y

# - name: install nodejs
#   ansible.builtin.dnf:
#     name: nodejs
#     state: installed

# - name: install dependecies packages
#   community.general.npm:
#     path: /app



- name: disable default nodejs
  ansible.builtin.command: dnf module disable nodejs -y

- name: enable nodejs:20
  ansible.builtin.command: dnf module enable nodejs:20 -y

- name: Install nodejs
  ansible.builtin.dnf:
    name: nodejs
    state: present

- name: install dependencies
  community.general.npm:
    path: /app